version: '3.4'

services:
    connect-four-referee:
        image: marein/php-gaming-website:php-fpm
        command: bin/console gaming:consume-messages -c connect-four.referee
        env_file: ../app.env
        volumes:
            - proxysql.sock:/var/run/proxysql
        deploy:
            replicas: 15
            placement:
                constraints:
                    - "node.labels.long-running==1"

volumes:
    proxysql.sock:
