version: '3.4'

services:
    mysql-connect-four-3:
        image: marein/php-gaming-website:mysql
        command: mysqld --max-connections=1000
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - mysql-connect-four-3:/var/lib/mysql
        deploy:
            placement:
                constraints:
                    - "node.labels.mysql-connect-four-3==1"
    mysql-connect-four-3-exporter:
        image: prom/mysqld-exporter
        environment:
            DATA_SOURCE_NAME: "root:password@(mysql-connect-four-3:3306)/"
        deploy:
            placement:
                constraints:
                    - "node.labels.mysql-connect-four-3==1"
            labels:
                - "prometheus-job=mysql"
                - "prometheus-port=9104"

volumes:
    mysql-connect-four-3:
