version: '3.4'

services:
    connect-four-mysql-1:
        image: marein/php-gaming-website:mysql
        command: mysqld --max-connections=1000
        environment:
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - connect-four-mysql-1:/var/lib/mysql
        deploy:
            placement:
                constraints:
                    - "node.labels.connect-four-mysql-1==1"
    connect-four-mysql-1-exporter:
        image: prom/mysqld-exporter
        environment:
            DATA_SOURCE_NAME: "root:password@(connect-four-mysql-1:3306)/"
        deploy:
            placement:
                constraints:
                    - "node.labels.connect-four-mysql-1==1"
            labels:
                - "prometheus-job=mysql"
                - "prometheus-port=9104"

volumes:
    connect-four-mysql-1:
