services:

    chat.chat-controller:
        class: Gaming\Chat\Presentation\Http\ChatController
        public: false
        arguments:
            - '@chat.command-bus'
            - '@chat.query-bus'

    chat.chat-gateway:
        class: Gaming\Chat\Infrastructure\DoctrineChatGateway
        public: false
        arguments:
            - '@chat.doctrine-dbal'
            - 'chat'
            - 'message'

    chat.chat-service:
        class: Gaming\Chat\Application\ChatService
        public: false
        arguments:
            - '@chat.chat-gateway'
            - '@chat.event-store'
