services:
    chat.chat-controller:
        class: Gaming\Chat\Presentation\Http\ChatController
        arguments: ['@chat.command-bus', '@chat.query-bus']

    chat.chat-gateway:
        class: Gaming\Chat\Infrastructure\DoctrineChatGateway
        arguments: ['@chat.doctrine-dbal', 'chat', 'message']

    chat.idempotent-chat-id-storage:
        class: Gaming\Common\IdempotentStorage\PredisIdempotentStorage
        arguments: ['@chat.predis', 86400]

    chat.chat-service:
        class: Gaming\Chat\Application\ChatService
        arguments: ['@chat.chat-gateway', '@chat.event-store', '@clock', '@chat.idempotent-chat-id-storage']
