services:

    # The following definitions decorate the routing command bus. This could be done with a factory object.
    chat.command-bus:
        class: Gaming\Common\Bus\Integration\SymfonyValidatorBus
        public: false
        arguments:
            - '@chat.doctrine-transactional-command-bus'
            - '@validator'

    chat.doctrine-transactional-command-bus:
        class: Gaming\Common\Bus\Integration\DoctrineTransactionalBus
        public: false
        arguments:
            - '@chat.routing-command-bus'
            - '@chat.doctrine-dbal'

    # This is pretty ugly. We can use tags, or create this via a factory in php.
    chat.routing-command-bus:
        class: Gaming\Common\Bus\RoutingBus
        public: false
        arguments:
            -
                'Gaming\Chat\Application\Command\InitiateChatCommand': ['@chat.chat-service', 'initiateChat']
                'Gaming\Chat\Application\Command\WriteMessageCommand': ['@chat.chat-service', 'writeMessage']
