services:
    chat.command-bus:
        class: Gaming\Common\Bus\RoutingBus
        arguments:
            -   'Gaming\Chat\Application\Command\InitiateChatCommand': ['@chat.chat-service', 'initiateChat']
                'Gaming\Chat\Application\Command\WriteMessageCommand': ['@chat.chat-service', 'writeMessage']

    chat.transactional-command-bus:
        class: Gaming\Common\Bus\Integration\DoctrineTransactionalBus
        decorates: 'chat.command-bus'
        arguments: ['@.inner', '@chat.doctrine-dbal']

    chat.validating-command-bus:
        class: Gaming\Common\Bus\Integration\SymfonyValidatorBus
        decorates: 'chat.command-bus'
        arguments: ['@.inner', '@validator']
