services:
    chat.command-bus:
        alias: gaming_platform_bus.chat_command

    chat.transactional-command-bus:
        class: Gaming\Common\Bus\Integration\DoctrineTransactionalBus
        decorates: 'chat.command-bus'
        arguments: ['@.inner', '@chat.doctrine-dbal']

    chat.validating-command-bus:
        class: Gaming\Common\Bus\Integration\SymfonyValidatorBus
        decorates: 'chat.command-bus'
        arguments: ['@.inner', '@validator']
