services:

    # This is pretty ugly. We can use tags, or create this via a factory in php.
    chat.query-bus:
        class: Gaming\Common\Bus\Integration\SymfonyValidatorBus
        public: false
        arguments:
            - '@chat.routing-query-bus'
            - '@validator'

    chat.routing-query-bus:
        class: Gaming\Common\Bus\RoutingBus
        public: false
        arguments:
            -
                'Gaming\Chat\Application\Query\MessagesQuery': ['@chat.chat-service', 'messages']
