imports: [{ resource: services/ }]

gaming_platform_bus:
    buses:
        chat_command: ~
        chat_query: ~

doctrine:
    dbal:
        connections:
            chat:
                url: '%env(APP_CHAT_DOCTRINE_DBAL_URL)%'
                server_version: '8.2'
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
