#!/usr/bin/env bash

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

docker build --target=php-cli -t marein/php-gambling-website:php-cli .
docker build --target=php-fpm -t marein/php-gambling-website:php-fpm .
docker build --target=nginx -t marein/php-gambling-website:nginx .
docker build --target=nchan -t marein/php-gambling-website:nchan .
docker build --target=mysql -t marein/php-gambling-website:mysql .
docker build --target=redis -t marein/php-gambling-website:redis .
docker build --target=rabbit-mq -t marein/php-gambling-website:rabbit-mq .

docker push marein/php-gambling-website:php-cli
docker push marein/php-gambling-website:php-fpm
docker push marein/php-gambling-website:nginx
docker push marein/php-gambling-website:nchan
docker push marein/php-gambling-website:mysql
docker push marein/php-gambling-website:redis
docker push marein/php-gambling-website:rabbit-mq
