services:
    web-interface.security:
        class: Gaming\WebInterface\Infrastructure\Security\Security
        arguments: ['@security.helper', '@identity.command-bus']

    web-interface.security.user_provider:
        class: Gaming\WebInterface\Infrastructure\Security\UserProvider
        arguments: ['@identity.query-bus', '@clock']
