services:

  web-interface.security.user_argument_value_resolver:
    class: Gaming\WebInterface\Infrastructure\Security\UserArgumentValueResolver
    public: false
    arguments:
      - '@security.token_storage'
    tags:
      - { name: controller.argument_value_resolver }

  web-interface.security.user_provider:
    class: Gaming\WebInterface\Infrastructure\Security\UserProvider
    public: false

  web-interface.security.arrival_authenticator:
    class: Gaming\WebInterface\Infrastructure\Security\ArrivalAuthenticator
    public: false
    arguments:
      - '@web-interface.identity-service'
      - '@security.token_storage'
