version: '3.4'

x-php-container:
  &php-container
    image: marein/php-gaming-website:php-fpm
    env_file: ./app.env
    volumes:
        - proxysql.sock:/var/run/proxysql

services:
    web:
        <<: *php-container
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.labels.web==1"
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.web.priority=10"
                - "traefik.http.routers.web.rule=PathPrefix(`/`)"
                - "traefik.http.services.web.loadbalancer.server.port=80"
    connect-four-follow-event-store-message-broker-1:
        <<: *php-container
        command: bin/console connect-four:follow-event-store message-broker-1 -s publish-to-message-broker
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-projection-1:
        <<: *php-container
        command: bin/console connect-four:follow-event-store projection-1 -s game-projection -s games-by-player-projection -s running-games-projection -s open-games-projection -w 8
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-message-broker-2:
        <<: *php-container
        command: bin/console connect-four:follow-event-store message-broker-2 -s publish-to-message-broker
        environment:
            APP_CONNECT_FOUR_DOCTRINE_DBAL_DATABASE: "db2"
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-projection-2:
        <<: *php-container
        command: bin/console connect-four:follow-event-store projection-2 -s game-projection -s games-by-player-projection -s running-games-projection -s open-games-projection -w 8
        environment:
            APP_CONNECT_FOUR_DOCTRINE_DBAL_DATABASE: "db2"
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-message-broker-3:
        <<: *php-container
        command: bin/console connect-four:follow-event-store message-broker-3 -s publish-to-message-broker
        environment:
            APP_CONNECT_FOUR_DOCTRINE_DBAL_DATABASE: "db3"
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-projection-3:
        <<: *php-container
        command: bin/console connect-four:follow-event-store projection-3 -s game-projection -s games-by-player-projection -s running-games-projection -s open-games-projection -w 8
        environment:
            APP_CONNECT_FOUR_DOCTRINE_DBAL_DATABASE: "db3"
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-message-broker-4:
        <<: *php-container
        command: bin/console connect-four:follow-event-store message-broker-4 -s publish-to-message-broker
        environment:
            APP_CONNECT_FOUR_DOCTRINE_DBAL_DATABASE: "db4"
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-projection-4:
        <<: *php-container
        command: bin/console connect-four:follow-event-store projection-4 -s game-projection -s games-by-player-projection -s running-games-projection -s open-games-projection -w 8
        environment:
            APP_CONNECT_FOUR_DOCTRINE_DBAL_DATABASE: "db4"
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-message-broker-5:
        <<: *php-container
        command: bin/console connect-four:follow-event-store message-broker-5 -s publish-to-message-broker
        environment:
            APP_CONNECT_FOUR_DOCTRINE_DBAL_DATABASE: "db5"
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-follow-event-store-projection-5:
        <<: *php-container
        command: bin/console connect-four:follow-event-store projection-5 -s game-projection -s games-by-player-projection -s running-games-projection -s open-games-projection -w 8
        environment:
            APP_CONNECT_FOUR_DOCTRINE_DBAL_DATABASE: "db5"
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    chat-follow-event-store:
        <<: *php-container
        command: bin/console chat:follow-event-store pointer --select-all-subscribers
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    identity-follow-event-store:
        <<: *php-container
        command: bin/console identity:follow-event-store pointer --select-all-subscribers
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    connect-four-referee:
        <<: *php-container
        command: bin/console gaming:consume-messages -c connect-four.referee
        deploy:
            replicas: 15
            placement:
                constraints:
                    - "node.labels.long-running==1"
    chat-command:
        <<: *php-container
        command: bin/console gaming:consume-messages -c chat.command
        deploy:
            replicas: 15
            placement:
                constraints:
                    - "node.labels.long-running==1"
    web-interface-publish-to-browser:
        <<: *php-container
        command: bin/console gaming:consume-messages -c web-interface.publish-to-browser
        deploy:
            replicas: 20
            placement:
                constraints:
                    - "node.labels.long-running==1"
    web-interface-publish-running-games-count-to-nchan:
        <<: *php-container
        command: bin/console web-interface:publish-running-games-count-to-nchan
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"
    proxysql-sidecar:
        image: marein/php-gaming-website:proxysql
        environment:
            PROXYSQL_CONFIG: |
                admin_variables: {
                    restapi_enabled="true"
                }
                mysql_variables: {
                    interfaces="/var/run/proxysql/proxysql.sock"
                    server_version="8.0"
                    monitor_username="root"
                    monitor_password="password"
                    auto_increment_delay_multiplex=0
                    threads=8
                }
                mysql_servers: (
                    {hostgroup=1,address="mysql-connect-four-1",port=3306,max_connections=100},
                    {hostgroup=2,address="mysql-connect-four-2",port=3306,max_connections=100},
                    {hostgroup=3,address="mysql-connect-four-3",port=3306,max_connections=100},
                    {hostgroup=4,address="mysql-connect-four-4",port=3306,max_connections=100},
                    {hostgroup=5,address="mysql-connect-four-5",port=3306,max_connections=100}
                )
                mysql_users: (
                    {username="root",password="password",default_hostgroup=1}
                )
                mysql_query_rules: (
                    {rule_id=1,schemaname="db1",destination_hostgroup=1,apply=1},
                    {rule_id=2,schemaname="db2",destination_hostgroup=2,apply=1},
                    {rule_id=3,schemaname="db3",destination_hostgroup=3,apply=1},
                    {rule_id=4,schemaname="db4",destination_hostgroup=4,apply=1},
                    {rule_id=5,schemaname="db5",destination_hostgroup=5,apply=1},
                    {rule_id=6,match_pattern="^CREATE DATABASE(?: IF NOT EXISTS)? `db1`$$",replace_pattern="CREATE DATABASE IF NOT EXISTS `db1`",destination_hostgroup=1,apply=1},
                    {rule_id=7,match_pattern="^CREATE DATABASE(?: IF NOT EXISTS)? `db2`$$",replace_pattern="CREATE DATABASE IF NOT EXISTS `db2`",destination_hostgroup=2,apply=1},
                    {rule_id=8,match_pattern="^CREATE DATABASE(?: IF NOT EXISTS)? `db3`$$",replace_pattern="CREATE DATABASE IF NOT EXISTS `db3`",destination_hostgroup=3,apply=1},
                    {rule_id=9,match_pattern="^CREATE DATABASE(?: IF NOT EXISTS)? `db4`$$",replace_pattern="CREATE DATABASE IF NOT EXISTS `db4`",destination_hostgroup=4,apply=1},
                    {rule_id=10,match_pattern="^CREATE DATABASE(?: IF NOT EXISTS)? `db5`$$",replace_pattern="CREATE DATABASE IF NOT EXISTS `db5`",destination_hostgroup=5,apply=1}
                )
        volumes:
            - proxysql.sock:/var/run/proxysql
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.labels.needs-proxysql-sidecar==1"
            labels:
                - "prometheus-job=proxysql"
                - "prometheus-port=6070"
                - "prometheus-path=/metrics"

volumes:
    proxysql.sock:
