version: '3.4'

services:
    grafana:
        image: ghcr.io/gaming-platform/docker-grafana:10.0
        ports:
            - "8083:3000"
        deploy:
            placement:
                constraints:
                    - "node.labels.grafana==1"
    prometheus:
        image: ghcr.io/gaming-platform/docker-prometheus:2.45
        command: --config.file=/etc/prometheus/dockerswarm.yml
        volumes:
            - prometheus:/prometheus
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints:
                    - "node.labels.prometheus==1"
    node-exporter:
        image: prom/node-exporter:v1.6.0
        deploy:
            mode: global
            labels:
                - "prometheus-job=node"
                - "prometheus-port=9100"

volumes:
    prometheus:
