version: '3.4'

services:
    rabbit-mq:
        image: marein/php-gaming-website:rabbit-mq
        hostname: rabbit-mq
        volumes:
            - rabbit-mq:/var/lib/rabbitmq/mnesia
        deploy:
            placement:
                constraints:
                    - "node.labels.rabbit-mq==1"
            labels:
                - "prometheus-job=rabbitmq"
                - "prometheus-port=15692"
                - "prometheus-path=/metrics/per-object"

volumes:
    rabbit-mq:
