version: '3.4'

services:
    rabbitmq:
        image: ghcr.io/gaming-platform/docker-rabbitmq:3.12
        hostname: rabbitmq
        volumes:
            - rabbitmq:/var/lib/rabbitmq/mnesia
        deploy:
            placement:
                constraints:
                    - "node.labels.rabbitmq==1"
            labels:
                - "prometheus-job=rabbitmq"
                - "prometheus-port=15692"
                - "prometheus-path=/metrics/per-object"

volumes:
    rabbitmq:
