version: '3.4'

services:
    redis-connect-four:
        image: marein/php-gaming-website:redis
        command: redis-server --appendonly yes
        volumes:
            - redis-connect-four:/data
        deploy:
            placement:
                constraints:
                    - "node.labels.redis-connect-four==1"
    redis-connect-four-exporter:
        image: oliver006/redis_exporter
        command:
            - '-redis.addr=redis-connect-four:6379'
        deploy:
            placement:
                constraints:
                    - "node.labels.redis-connect-four==1"
            labels:
                - "prometheus-job=redis"
                - "prometheus-port=9121"

volumes:
    redis-connect-four:
