version: '3.4'

services:
    web-interface-http:
        image: marein/php-gaming-website:php-fpm
        env_file: ../app.env
        volumes:
            - proxysql.sock:/var/run/proxysql
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.labels.web-interface-http==1"
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.web-interface-http.priority=10"
                - "traefik.http.routers.web-interface-http.rule=PathPrefix(`/`)"
                - "traefik.http.services.web-interface-http.loadbalancer.server.port=80"
    web-interface-publish-to-browser:
        image: marein/php-gaming-website:php-fpm
        command: bin/console gaming:consume-messages web-interface.publish-to-browser -r 5
        env_file: ../app.env
        volumes:
            - proxysql.sock:/var/run/proxysql
        deploy:
            replicas: 20
            placement:
                constraints:
                    - "node.labels.long-running==1"
    web-interface-publish-running-games-count-to-nchan:
        image: marein/php-gaming-website:php-fpm
        command: bin/console web-interface:publish-running-games-count-to-nchan
        env_file: ../app.env
        volumes:
            - proxysql.sock:/var/run/proxysql
        deploy:
            placement:
                constraints:
                    - "node.labels.long-running==1"

volumes:
    proxysql.sock:
