version: '3.4'

services:
    web-interface-http:
        image: marein/php-gaming-website:php-fpm
        env_file: ../app.env
        volumes:
            - proxysql.sock:/var/run/proxysql
        deploy:
            mode: global
            placement:
                constraints:
                    - "node.labels.web-interface-http==1"
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.web-interface-http.priority=10"
                - "traefik.http.routers.web-interface-http.rule=PathPrefix(`/`)"
                - "traefik.http.services.web-interface-http.loadbalancer.server.port=80"

volumes:
    proxysql.sock:
