version: '3.4'

services:
    web-interface-redis:
        image: marein/php-gaming-website:redis
        command: redis-server --appendonly yes
        volumes:
            - web-interface-redis:/data
        deploy:
            placement:
                constraints:
                    - "node.labels.web-interface-redis==1"
    web-interface-redis-exporter:
        image: oliver006/redis_exporter
        command:
            - '-redis.addr=web-interface-redis:6379'
        deploy:
            placement:
                constraints:
                    - "node.labels.web-interface-redis==1"
            labels:
                - "prometheus-job=redis"
                - "prometheus-port=9121"

volumes:
    web-interface-redis:
