services:
    identity.command-bus:
        class: Gaming\Common\Bus\RoutingBus
        arguments:
            -   'Gaming\Identity\Application\User\Command\ArriveCommand': ['@identity.user-service', 'arrive']
                'Gaming\Identity\Application\User\Command\SignUpCommand': ['@identity.user-service', 'signUp']

    identity.transactional-command-bus:
        class: Gaming\Common\Bus\Integration\DoctrineTransactionalBus
        decorates: 'identity.command-bus'
        arguments: ['@.inner', '@identity.doctrine-dbal']

    identity.retry-command-bus:
        class: Gaming\Common\Bus\RetryBus
        decorates: 'identity.command-bus'
        arguments: ['@.inner', 3, 'Gaming\Common\Domain\Exception\ConcurrencyException']

    identity.validating-command-bus:
        class: Gaming\Common\Bus\Integration\SymfonyValidatorBus
        decorates: 'identity.command-bus'
        arguments: ['@.inner', '@validator']
