services:

    identity.follow-event-store-command:
        class: Gaming\Common\Port\Adapter\Symfony\FollowEventStoreCommand
        public: false
        arguments:
            - '@identity.event-store'
            - !service
                class: Gaming\Common\Port\Adapter\Symfony\EventStorePointerFactory\PredisEventStorePointerFactory
                arguments:
                    - '@identity.predis'
            - !tagged { tag: 'identity.stored-event-subscriber', index_by: 'key' }
        tags:
            - { name: console.command, command: identity:follow-event-store, description: 'Publish events to subscribers.' }
