services:
    identity.doctrine-dbal:
        alias: 'doctrine.dbal.identity_connection'

    identity.doctrine-orm:
        alias: 'doctrine.orm.identity_entity_manager'

    identity.event-store:
        class: Gaming\Common\EventStore\Integration\Doctrine\DoctrineEventStore
        arguments:
            - '@identity.doctrine-dbal'
            - 'event_store'
            - !service
                class: Gaming\Common\EventStore\Integration\JmsSerializer\JmsContentSerializer
                arguments: ['@identity.jms', 'Gaming\Common\Domain\DomainEvent']

    identity.orm.publish-domain-events-listener:
        class: Gaming\Common\EventStore\Integration\Doctrine\EventListener\AppendDomainEvents
        arguments: ['@identity.event-store']
        tags:
            - { name: doctrine.event_listener, event: postPersist, entity_manager: identity }
            - { name: doctrine.event_listener, event: postUpdate, entity_manager: identity }
            - { name: doctrine.event_listener, event: postRemove, entity_manager: identity }
