services:

    identity.predis:
        class: Predis\Client
        public: false
        arguments:
            - '%env(APPLICATION_IDENTITY_PREDIS_CLIENT_URL)%'
            -
                prefix: 'identity.'

    identity.doctrine-dbal:
        alias: 'doctrine.dbal.identity_connection'

    identity.doctrine-orm:
        alias: 'doctrine.orm.identity_entity_manager'

    identity.event-store:
        class: Gaming\Common\Port\Adapter\EventStore\DoctrineEventStore
        public: false
        arguments:
            - '@identity.doctrine-dbal'
            - 'event_store'
            - '@identity.normalizer'
