services:

    identity.doctrine-dbal:
        alias: 'doctrine.dbal.identity_connection'

    identity.doctrine-orm:
        alias: 'doctrine.orm.identity_entity_manager'

    identity.event-store:
        class: Gaming\Common\EventStore\Integration\Doctrine\DoctrineEventStore
        public: false
        arguments:
            - '@identity.doctrine-dbal'
            - 'event_store'
            - '@identity.normalizer'

    identity.orm.publish-domain-events-listener:
        class: Gaming\Common\Domain\Integration\Doctrine\PublishDomainEventsListener
        arguments:
            - '@identity.domain-event-publisher'
        tags:
            - { name: doctrine.event_listener, event: postPersist, entity_manager: identity }
            - { name: doctrine.event_listener, event: postUpdate, entity_manager: identity }
            - { name: doctrine.event_listener, event: postRemove, entity_manager: identity }
