services:

    identity.store-domain-events-subscriber:
        class: Gaming\Identity\Port\Adapter\Persistence\EventStore\StoreDomainEventsSubscriber
        public: false
        arguments:
            - '@identity.event-store'

    identity.publish-stored-events-subscriber:
        class: Gaming\Identity\Port\Adapter\Messaging\PublishStoredEventsToRabbitMqSubscriber
        public: false
        arguments:
            - '@gaming.message-broker'
        tags:
            - { name: 'identity.stored-event-subscriber', key: 'publish-to-message-broker' }
