services:
    identity.publish-stored-events-subscriber:
        class: Gaming\Identity\Port\Adapter\Messaging\PublishDomainEventsToMessageBrokerSubscriber
        arguments: ['@gaming.message-broker.gaming-exchange-publisher']
        tags: [{ name: 'identity.stored-event-subscriber', key: 'publish-to-message-broker' }]
