{
 "title": "PHP-FPM Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(app_instance_name, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_http_requests_total{action=\"all\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Status Codes Last Hour",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(app_http_2xx_responses_total{action=\"all\", instance=~\"$instance\"}[1h]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "increase(app_http_4xx_responses_total{action=\"all\"}[1h])",
     "legendFormat": "4xx"
    },
    {
     "expr": "increase(app_http_5xx_responses_total{action=\"all\"}[1h])",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Total Requests Last Hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(app_http_requests_total{action!=\"all\", instance=~\"$instance\"}[1h])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Requests / s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_http_requests_total{action=\"all\", instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Average Response Time Last Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\n    rate(app_request_durations_histogram_seconds_sum{action!=\"all\", instance=~\"$instance\"}[1h])\n) by (action)\n/\nsum(\n    rate(app_request_durations_histogram_seconds_count{action!=\"all\", instance=~\"$instance\"}[1h])\n) by (action)\n",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Percentile 0.95 Last Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n        rate(app_request_durations_histogram_seconds_bucket{action!=\"all\", instance=~\"$instance\"}[1h])\n    ) by (action, le)\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}