{
 "title": "Redis Overview",
 "description": "Visualizes Redis metrics.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(redis_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_uptime_in_seconds{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(100 * (redis_memory_used_bytes{instance=~\"$instance\"} / redis_memory_max_bytes{instance=~\"$instance\"}))"
    }
   ]
  },
  {
   "title": "Total Commands / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_total{instance=~\"$instance\"} [$__rate_interval])) by (cmd)",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Hits & Misses / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_keyspace_hits_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Hits, {{ instance }}"
    },
    {
     "expr": "rate(redis_keyspace_misses_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "Misses, {{ instance }}"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Used, {{ instance }}"
    },
    {
     "expr": "redis_memory_max_bytes{instance=~\"$instance\"}",
     "legendFormat": "Max, {{ instance }}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_net_input_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Input"
    },
    {
     "expr": "sum(rate(redis_net_output_bytes_total{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Total Items Per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=~\"$instance\"}) by (db, instance)",
     "legendFormat": "{{ db }}, {{ instance }}"
    }
   ]
  },
  {
   "title": "Expiring & Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_db_keys{instance=~\"$instance\"}) by (instance) - sum(redis_db_keys_expiring{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Not Expiring, {{ instance }}"
    },
    {
     "expr": "sum(redis_db_keys_expiring{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Expiring, {{ instance }}"
    }
   ]
  },
  {
   "title": "Expired & Evicted Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "Expired, {{ instance }}"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{instance=~\"$instance\"}[5m])) by (instance)",
     "legendFormat": "Evicted, {{ instance }}"
    }
   ]
  },
  {
   "title": "Connected & Blocked Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(redis_connected_clients{instance=~\"$instance\"})",
     "legendFormat": "Connected"
    },
    {
     "expr": "sum(redis_blocked_clients{instance=~\"$instance\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Average Time Spent By Command / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{instance =~ \"$instance\"}[$__rate_interval])) by (cmd)\n /\nsum(rate(redis_commands_total{instance =~ \"$instance\"}[$__rate_interval])) by (cmd)\n",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  {
   "title": "Total Time Spent By Command / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_commands_duration_seconds_total{instance=~\"$instance\"}[$__rate_interval])) by (cmd) != 0",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}