{
 "title": "Traefik Overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(traefik_service_requests_total, instance)"
    }
   },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Requests Last 5 Minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Last Hour",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\"}[1h])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "service" },
  {
   "title": "Average Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"$service\"}) / sum(traefik_service_requests_total{service=\"$service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Requests / s",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Last 5 Minutes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Last 5 Minutes",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "repeat": "services",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[5m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Last 30 Minutes",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[30m])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Codes Last Hour",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{job=\"traefik\", instance=\"$instance\", service=\"$service\"}[1h])) by (code)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}