imports:
    - { resource: config.yml }

framework:
    profiler:
        only_exceptions: false
    router:
        resource: "%kernel.project_dir%/config/routing_dev.yml"

web_profiler:
    toolbar: true

monolog:
    handlers:
        application_stream:
            level: debug
            channels: ['!event']

services:
    Gaming\Common\EventStore\Integration\Doctrine\SkipDebugMatchingSqlPatternLogger:
        decorates: 'monolog.logger.doctrine'
        arguments:
            - '@.inner'
            - ['/^SELECT.*FROM event_store .*WHERE.*id >/']

    Gaming\Common\MessageBroker\EventListener\DebugEvents:
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_listener, method: 'messageReceived' }
            - { name: kernel.event_listener, method: 'messageHandled' }
            - { name: kernel.event_listener, method: 'messageSent' }
            - { name: kernel.event_listener, method: 'messagesFlushed' }
            - { name: kernel.event_listener, method: 'replySent' }
            - { name: kernel.event_listener, method: 'requestSent' }
