imports:
    - { resource: config.yml }

framework:
    profiler:
        only_exceptions: false
    router:
        resource: "%kernel.project_dir%/config/routing_dev.yml"

web_profiler:
    toolbar: true

monolog:
    handlers:
        debug_stream:
            type: stream
            path: 'php://stderr'
            level: debug
            formatter: 'monolog.formatter.json'
            channels: ['app', 'php']
            bubble: false
        error_stream:
            type: stream
            path: 'php://stderr'
            formatter: 'monolog.formatter.json'
            level: error
