global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'connect-four'
    scrape_interval: 5s
    metrics_path: '/metrics/connect-four'
    static_configs:
      - targets: ['traefik']
