global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'dockerswarm'
    scrape_interval: 5s
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        regex: .+
        action: keep
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        target_label: job
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_path ]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [ __address__, __meta_dockerswarm_service_label_prometheus_port ]
        target_label: __address__
        separator: ';'
        regex: '([^:]+):\d+;(\d+)'
        replacement: '${1}:${2}'
      - source_labels: [ __meta_dockerswarm_service_mode, __meta_dockerswarm_node_hostname ]
        target_label: instance
        separator: ';'
        regex: 'global;(.*)'
        replacement: '${1}'
      - source_labels: [ __meta_dockerswarm_service_mode, __meta_dockerswarm_service_name ]
        target_label: instance
        separator: ';'
        regex: 'replicated;(.*)'
        replacement: '${1}'
