services:
    connect-four.command-bus:
        class: Gaming\Common\Bus\Psr11RoutingBus
        arguments: [!tagged_locator { tag: 'connect-four.command-bus.handler', index_by: 'key' }]

    connect-four.retry-command-bus:
        class: Gaming\Common\Bus\RetryBus
        decorates: 'connect-four.command-bus'
        arguments: ['@.inner', 3,'Gaming\Common\Domain\Exception\ConcurrencyException']

    connect-four.validating-command-bus:
        class: Gaming\Common\Bus\Integration\SymfonyValidatorBus
        decorates: 'connect-four.command-bus'
        arguments: ['@.inner', '@validator']

    Gaming\ConnectFour\Application\Game\Command\AbortHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: connect-four.command-bus.handler, key: Gaming\ConnectFour\Application\Game\Command\AbortCommand }]

    Gaming\ConnectFour\Application\Game\Command\ResignHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: connect-four.command-bus.handler, key: Gaming\ConnectFour\Application\Game\Command\ResignCommand }]

    Gaming\ConnectFour\Application\Game\Command\AssignChatHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: connect-four.command-bus.handler, key: Gaming\ConnectFour\Application\Game\Command\AssignChatCommand }]

    Gaming\ConnectFour\Application\Game\Command\JoinHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: connect-four.command-bus.handler, key: Gaming\ConnectFour\Application\Game\Command\JoinCommand }]

    Gaming\ConnectFour\Application\Game\Command\MoveHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: connect-four.command-bus.handler, key: Gaming\ConnectFour\Application\Game\Command\MoveCommand }]

    Gaming\ConnectFour\Application\Game\Command\OpenHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: connect-four.command-bus.handler, key: Gaming\ConnectFour\Application\Game\Command\OpenCommand }]
