services:

    # The following definitions decorate the routing command bus. This could be done with a factory object.
    connect-four.command-bus:
        class: Gaming\Common\Bus\Integration\SymfonyValidatorBus
        public: false
        arguments:
            - '@connect-four.retry-command-bus'
            - '@validator'

    connect-four.retry-command-bus:
        class: Gaming\Common\Bus\RetryBus
        public: false
        arguments:
            - '@connect-four.routing-command-bus'
            - 3
            - 'Gaming\Common\Domain\Exception\ConcurrencyException'

    # This is pretty ugly. We can use tags, or create this via a factory in php.
    connect-four.routing-command-bus:
        class: Gaming\Common\Bus\RoutingBus
        public: false
        arguments:
            -
                'Gaming\ConnectFour\Application\Game\Command\AbortCommand': '@connect-four.command.abort-handler'
                'Gaming\ConnectFour\Application\Game\Command\ResignCommand': '@connect-four.command.resign-handler'
                'Gaming\ConnectFour\Application\Game\Command\AssignChatCommand': '@connect-four.command.assign-chat-handler'
                'Gaming\ConnectFour\Application\Game\Command\JoinCommand': '@connect-four.command.join-handler'
                'Gaming\ConnectFour\Application\Game\Command\MoveCommand': '@connect-four.command.move-handler'
                'Gaming\ConnectFour\Application\Game\Command\OpenCommand': '@connect-four.command.open-handler'

    connect-four.command.abort-handler:
        class: Gaming\ConnectFour\Application\Game\Command\AbortHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.resign-handler:
        class: Gaming\ConnectFour\Application\Game\Command\ResignHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.assign-chat-handler:
        class: Gaming\ConnectFour\Application\Game\Command\AssignChatHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.join-handler:
        class: Gaming\ConnectFour\Application\Game\Command\JoinHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.move-handler:
        class: Gaming\ConnectFour\Application\Game\Command\MoveHandler
        public: false
        arguments:
            - '@connect-four.game-repository'

    connect-four.command.open-handler:
        class: Gaming\ConnectFour\Application\Game\Command\OpenHandler
        public: false
        arguments:
            - '@connect-four.game-repository'
