services:
    connect-four.command-bus:
        alias: gaming_platform_bus.connect_four_command

    connect-four.retry-command-bus:
        class: Gaming\Common\Bus\RetryBus
        decorates: 'connect-four.command-bus'
        arguments: ['@.inner', 3,'Gaming\Common\Domain\Exception\ConcurrencyException']

    connect-four.validating-command-bus:
        class: Gaming\Common\Bus\Integration\SymfonyValidatorBus
        decorates: 'connect-four.command-bus'
        arguments: ['@.inner', '@validator']

    Gaming\ConnectFour\Application\Game\Command\AbortHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: 'gaming_platform_bus.handler', bus: 'connect_four_command' }]

    Gaming\ConnectFour\Application\Game\Command\ResignHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: 'gaming_platform_bus.handler', bus: 'connect_four_command' }]

    Gaming\ConnectFour\Application\Game\Command\AssignChatHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: 'gaming_platform_bus.handler', bus: 'connect_four_command' }]

    Gaming\ConnectFour\Application\Game\Command\JoinHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: 'gaming_platform_bus.handler', bus: 'connect_four_command' }]

    Gaming\ConnectFour\Application\Game\Command\MoveHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: 'gaming_platform_bus.handler', bus: 'connect_four_command' }]

    Gaming\ConnectFour\Application\Game\Command\OpenHandler:
        arguments: ['@connect-four.game-repository']
        tags: [{ name: 'gaming_platform_bus.handler', bus: 'connect_four_command' }]
