version: '3'

server:
  command: 'php ../../public/index.php'
  user: www-data
  group: www-data
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  fcgi:
    address: unix:///var/run/php-fpm.sock
  pool:
    num_workers: ${PHP_FPM_PM_MAX_CHILDREN:-4}
    debug: true
  middleware: ['static']
  static: { dir: ../../public, forbid: ['.php'] }

logs:
  mode: development
  channels:
    http: { level: debug }
    server: { level: debug, mode: raw }
    metrics: { level: debug }
