services:
    shared.usernames:
        class: Gaming\Common\Usernames\Integration\InProcessUsernames
        arguments: ['@identity.query-bus']

    shared.usernames.cache:
        class: Gaming\Common\Usernames\Integration\CachedUsernames
        decorates: 'shared.usernames'
        arguments:
            - '@.inner'
            - 60
