name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  pipeline:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: ./project buildProductionImages

      - name: Testsuite
        run: |
          docker-compose -f docker-compose.ci.yml run php vendor/bin/codecept run unit
          docker-compose -f docker-compose.ci.yml run php vendor/bin/phpcs
          docker-compose -f docker-compose.ci.yml run php vendor/bin/phpstan analyse
          docker-compose -f docker-compose.ci.yml up -d
          docker-compose -f docker-compose.ci.yml run php bash -c 'wait-for-tcp-server php-fpm:9000 120 && vendor/bin/codecept run acceptance'
          docker-compose -f docker-compose.ci.yml down -v

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: ./project pushProductionImages
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
