name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  pipeline:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        run: ./project buildProductionImages

      - name: Testsuite
        run: ./project tests

      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: ./project pushProductionImages
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
